### PR TITLE
feat: Add callable functions

### PR DESCRIPTION
**Pull request by MaxAuer**
### Added support for callable functions.

They follow the same principle as reactive functions:
Create subfolder `callable`. Within that folder create a file `filename.callable.ts`. 

### Documentation

I wrote a small section in the documentation to make the usage clear. I used Flutter for the example.

## Tested

- [x] I tested the functionality locally via `npm link`
- [x] Added documentation in README.md

## Refrences

This PR adds support for #25

### CODE REVIEW

**Comment by MaxAuer** [comment]
Having played around with the .callable feature I am actually starting to question if this is even needed.

When we write a function and postfix it with `.function.ts` it gets exported. I am not sure if this actually adds value or if the docs just need to be more clear that a callable, schedule, etc. will get exported when postfixed with `.function`.

On the other side `.callable` makes it more clear what this function is about. But this should also be clear when the function is placed in a `callable` folder.

**Comment by FilledStacks** [comment]
@MaxAuer you're rights. It will get exported either way but as apart of the "reactive functions" .We'll need to do some naming and logging changes internally to align what it's doing and what it will be exported as. 

The readme will also have to be updated to reflect the additional function types. We can leave it as .function, that makes sense. Or what do you think? We'll just have an opinionated guide to put it in a callable folder for maintenance reasons.

**Comment by MaxAuer** [comment]
@FilledStacks I totaly agree. I think the documentation should be opinionated and we keep the `.function` extension for all Firebase internal endpoints (functions/schedule/callables...).

The parser does output the path already so basically we just need to remove the Reactive from the `Reactive Function - ...` part.

I think this issue is really just a documentation part and not something we need to address with code. It would make the current solution more complex than needed.

If you agree I would close this PR.

**Comment by FilledStacks** [comment]
@MaxAuer I think we can remove the code part and update the readme part to explain how it works and that it also uses the `.function` in the filename. Then that should be it really.

**Comment by MaxAuer** [comment]
As discussed we close this PR and make using the backend for callables etc more clear in the readme.

**Pull request closed without merging**
