### PR TITLE
Housekeeping 

### PR DESCRIPTION
**Pull request by mxttwoods**
Saw this on Youtube and couldn't resist helping out. 
Please let me know how else I can help or if there's a roadmap I can view. 

- ran ```npx prettier --write .```
- ran ```npx @mxttwoods/readme-cli```
- added jsdoc comments from usage
- added more prettier config opts
- ran ```ncu -u``` update deps

Matthew Woods

### CODE REVIEW

**Comment by mxttwoods** [comment]
- ran ```npx prettier --write .```
- ran @mxttwoods/readme-cli
- added jsdoc comments from usage
- added more prettier config opts

**Comment by mxttwoods** [comment]
- Updated Deps

**Review by FilledStacks — APPROVED** [review]
Thank you @mxttwoods I really appreciate this. The only thing that's next is to actually write out the readme instructions to use the project. I have a full written tutorial for it already but it's a bit too elaborate.

**Comment by mxttwoods** [comment]
This one may be worth a vuepress or dumi site!

Also, I'll make some more pr's to help with maintenance.

**Pull request merged**
