### PR TITLE
Add options interface and cors support

### PR DESCRIPTION
**Pull request by r0hit-gupta**
**BREAKING CHANGE**

The Function Parser now accepts `ParserOptions` as a parameter instead of booleans to make it easy to pass in optional values to the constructor.

### CODE REVIEW

**Comment by adamschnaare** [comment]
I like it, I think the cors option is partially what we'll need for https://github.com/FilledStacks/firebase-backend/issues/22 as well.

**Comment by FilledStacks** [comment]
The readme has to be updated for this as well.

We need a basic example of using the options and what it's for.

**Comment by FilledStacks** [comment]
@r0hit-gupta can you update the readme to match the new required functionality for this please

**Comment by FilledStacks** [comment]
I'll merge this in and then I'll update the readme since we need this for some of our backend work we're doing.

**Review by FilledStacks — APPROVED** [review]

**Pull request merged**
